[Update] Pebblo UI documentation added.
daxa-ai/pebblo pull request #243
Opened 2024-02-28 13:27 UTC by KumarNitin19

- Pebblo UI documentation added.

2024-02-29 05:32 UTC, rutujaac submitted a review, later dismissed
LGTM

2024-02-29 08:26 UTC, shreyas-damle requested changes
Please rebase this with main and add UI as a sub section within Pebblo section.

2024-03-04 07:05 UTC, KumarNitin19 commented on docs/gh_pages/docs/installation.md
> +Pebblo server now listens to `localhost:8000` to accept Gen-AI application data snippets for inspection and reporting. Pebblo UI interface would be available on `http://localhost:8000/pebblo `
@shreyas-damle Comment resolved

2024-03-04 07:05 UTC, KumarNitin19 commented on docs/gh_pages/docs/config.md
> +2. By default `Pebblo UI` runs at `localhost:8000/pebblo`. When we change values of `port` and/or `host`, the Pebblo UI would be running on the respective `url/pebblo`.
@shreyas-damle Comment resolved

2024-03-05 04:18 UTC, shreyas-damle approved these changes

2024-03-05 04:23 UTC, rutujaac approved these changes

2024-03-05 04:39 UTC, merged