Sharepoint loader
daxa-ai/pebblo pull request #361
Opened 2024-04-30 04:34 UTC by arpitkumar980

2024-04-30 09:24 UTC, Raj725 commented
@arpitkumar980 Do we need to set any env variables to run these samples?

2024-04-30 09:34 UTC, Raj725 reviewed
Please add a basic README

2024-04-30 09:34 UTC, Raj725 commented on pebblo_safeloader/langchain/identity-rag-sharepoint/pebblo_identity_safeload_sharepoint.py
> +            SharePointLoader(
Have these samples been tested? I am getting the following error on this line:
```
pebblo/pebblo_safeloader/langchain/identity-rag-sharepoint/pebblo_identity_safeload_sharepoint.py", line 30, in load_documents
      SharePointLoader(
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1066, in pydantic.main.validate_model
  File "pydantic/fields.py", line 439, in pydantic.fields.ModelField.get_default
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for _O365Settings
client_id
  field required (type=value_error.missing)
client_secret
  field required (type=value_error.missing)
```

2024-04-30 14:31 UTC, arpitkumar980 commented
yes we need config for this

2024-05-08 10:55 UTC, Raj725 requested changes
Update the samples to match the latest sample in the main branch, test it, and then we can merge this PR.

2024-05-08 10:55 UTC, Raj725 commented on pebblo_saferetriever/langchain/identity-rag-sharepoint/pebblo_identity_rag_sharepoint.py
> +        return PebbloRetrievalQA.from_chain_type(
@arpitkumar980 Update the initialization of `PebbloSafeLoader` and `PebbloRetrievalQA` to match the [latest sample in the main branch](https://github.com/daxa-ai/pebblo/blob/main/pebblo_saferetriever/langchain/identity-n-semantic-rag/semantic_rag.py), and then we can merge this PR.

2024-06-18 05:19 UTC, srics commented
Superseded by https://github.com/daxa-ai/pebblo/pull/399. Closing.

2024-06-18 05:19 UTC, closed without merging